default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: image_resizer_development

test:
  <<: *default
  database: image_resizer_test

production:
  <<: *default
  database: image_resizer_production
